ports:
  http: 28012
  admin: 28013
  rpc: 28014

server:
  port: ${ports.http}
  shutdown: graceful


logging:
  config: classpath:log4j2-spring.xml

# 服务管理配置
management:
  server:
    port: ${ports.admin}
  endpoints:
    #    enabled-by-default: true
    web:
      exposure:
        include:
          - 'groovy'
      #       - '*'
      base-path: /admin